export const MENU = [
  {
    id: "futomaki_filadelfia",
    name: "Filadelfia",
    price: 37,
    description: "Łosoś, serek, awokado, ogórek",
    category: "Futomaki",
    image: "/images/fut.filadelfia.webp",
  },
  {
    id: "futomaki_pieczony_losos",
    name: "Pieczony Łosoś",
    price: 38,
    description: "Łosoś w glazurze, serek, kanpyo, ogórek, sos kabayaki, sezam",
    category: "Futomaki",
    image: "/images/fut.pieczony-losos.webp",
  },
  {
    id: "futomaki_tunczyk",
    name: "Tuńczyk",
    price: 42,
    description:
      "Tuńczyk w marynacie den miso, majonez grzybowy, boczniak, jarmuż, chips z topinamburu",
    category: "Futomaki",
    image: "/images/fut.tuna.webp",
  },
  {
    id: "futomaki_krewetka",
    name: "Krewetka w tempurze",
    price: 38,
    description: "Krewetka w tempurze, ogórek, oshinko, siano z pora, sos kobe",
    category: "Futomaki",
    image: "/images/kr.w.t.webp",
  },
  {
    id: "futomaki_kalmar",
    name: "Kalmar w tempurze",
    price: 37,
    description:
      "Kalmar w tempurze, sos kobe, chutney z czerwonej cebuli, szczypiorek, jarmuż, kiszony musztardowie, sambal",
    category: "Futomaki",
    image: "/images/fut.kalmar-w-tempurze.webp",
  },
  {
    id: "futomaki_halibut",
    name: "Pieczony halibut",
    price: 39,
    description:
      "Halibut kombujime opalany z den miso, sos kobe, szczypiorek, karmelizowana gruszka, awokado",
    category: "Futomaki",
    image: "/images/k.w.t.webp",
  },
  {
    id: "futomaki_wegorz",
    name: "Węgorz",
    price: 40,
    description:
      "Grillowany węgorz unagi w tempurze, serek, malina, szczypiorek, sos kabayaki, matcha",
    category: "Futomaki",
    image: "/images/f.wegorz.webp",
  },
  {
    id: "Hosomaki_ryba",
    name: "Hosomaki warzywne",
    price: 40,
    description:
      "Grillowany węgorz unagi w tempurze, serek, malina, szczypiorek, sos kabayaki, matcha",
    category: "Hosomaki",
    image: "/images/hoso-tuna.webp",
  },
  {
    id: "Hosomaki_warzywne",
    name: "Hosomaki z rybą",
    price: 40,
    description:
      "Grillowany węgorz unagi w tempurze, serek, malina, szczypiorek, sos kabayaki, matcha",
    category: "Hosomaki",
    image: "/images/hoso1.webp",
  },
  {
    id: "uramaki_dragon",
    name: "Dragon",
    price: 62,
    description:
      "Krewetka w tempurze, awokado, grillowany węgorz unagi, sosy orzechowy i kabayaki, sezam",
    category: "Uramaki",
    image: "https://placehold.co/300x200?text=Dragon",
  },
  {
    id: "uramaki_rainbow",
    name: "Rainbow",
    price: 65,
    description: "Łosoś, sos kobe, awokado, owinięte rybami, ikura",
    category: "Uramaki",
    image: "https://placehold.co/300x200?text=Rainbow",
  },
  {
    id: "uramaki_geisha",
    name: "Geisha",
    price: 62,
    description:
      "Krewetka w tempurze, serek, kanpyo, ogórek, owinięte awokado, marynowana dynia, masago arare",
    category: "Uramaki",
    image: "https://placehold.co/300x200?text=Geisha",
  },
  {
    id: "sashimi_gravlax",
    name: "Gravlax",
    price: 55,
    description:
      "Gravlax, pesto z edamame, ogórek, awokado, marynowana dynia, rukola, ikura",
    category: "Sashimi Roll",
    image: "https://placehold.co/300x200?text=Gravlax",
  },
  {
    id: "sashimi_tunczyk",
    name: "Tuńczyk",
    price: 62,
    description:
      "Tuńczyk, majonez grzybowy, boczniak, pak choi, ogórek, szczypiorek, kizami wasabi",
    category: "Sashimi Roll",
    image: "https://placehold.co/300x200?text=Tuńczyk+Sashimi",
  },
  {
    id: "wege_tofu",
    name: "Smoking Tofu Sashimi Roll 6szt.",
    price: 39,
    description:
      "Wędzone tofu, marchewka smażona w sosie śliwkowym, szczypiorek, awokado, chutney z czerownej cebuli, masago arare",
    category: "Sushi Wege",
    image: "/images/wege/tofu.webp",
  },
  {
    id: "wege_tofu",
    name: "Smoking Filadelfia 6szt.",
    price: 32,
    description: "Marchewka sous vide, serek, ogórek, awokado, kanpyo",
    category: "Sushi Wege",
    image: "/images/wege/vege-filadelfia.webp",
  },
  {
    id: "wege_autumn",
    name: "Smoking Autumn 6szt.",
    price: 29,
    description:
      "Boczniak w tempurze, pesto z edamame, marynowana dynia, grzyby shimeji, ogórek sous vide, serek, ogórek, awokado, kanpyo",
    category: "Sushi Wege",
    image: "/images/wege/wege-autumn.png",
  },
  {
    id: "specjal_jakub",
    name: "Małże Św. Jakuba",
    price: 59,
    description: "Tatar z małży Św. Jakuba, sos kobe, por, smażone w tempurze",
    category: "Specjały Szajnochy",
    image: "https://placehold.co/300x200?text=Jakub",
  },
  {
    id: "specjal_osmiornica",
    name: "Ośmiornica",
    price: 79,
    description:
      "Macka ośmiornicy smażona na maśle miso, majonez grzybowy, boczniak, czosnkowe panko",
    category: "Specjały Szajnochy",
    image: "https://placehold.co/300x200?text=Ośmiornica",
  },
  {
    id: "zestaw_1",
    name: "Zestaw I (8szt.)",
    price: 100,
    description: "Nigiri: łosoś, tuńczyk, węgorz, krewetka (po 2 szt.)",
    category: "Zestawy",
    image: "https://placehold.co/300x200?text=Zestaw+I",
  },
  {
    id: "zestaw_6",
    name: "Zestaw VI (40szt.)",
    price: 250,
    description:
      "Filadelfia, krewetka w tempurze, hosomaki, Dragon, Shogun, panko z tatarem",
    category: "Zestawy",
    image: "https://placehold.co/300x200?text=Zestaw+VI",
  },
  {
    id: "tatar_losos",
    name: "Tatar z łososia",
    price: 40,
    description: "Tatar z łososia na maki w panko, sos kobe, szczypiorek",
    category: "Tatary",
    image: "https://placehold.co/300x200?text=Tatar+Łosoś",
  },
  {
    id: "tatar_tunczyk",
    name: "Tatar z tuńczyka",
    price: 48,
    description:
      "Tatar z tuńczyka na maki w panko, majonez grzybowy, piklowana cebula",
    category: "Tatary",
    image: "https://placehold.co/300x200?text=Tatar+Tuńczyk",
  },
  {
    id: "nigiri_warzywne",
    name: "Nigiri warzywne 1szt.",
    price: 8,
    description: "Tradycyjna forma sushi, warzywa na ryżu",
    category: "Nigiri",
    image: "/images/Nigiri/nigiri-awokado.webp",
  },
  {
    id: "nigiri_losos",
    name: "Nigiri łosoś 1szt.",
    price: 15,
    description: "Tradycyjna forma sushi, łosoś na ryżu",
    category: "Nigiri",
    image: "/images/Nigiri/nigiri-losos.webp",
  },
  {
    id: "nigiri_krewetka 1szt.",
    name: "Nigiri krewetka 1szt.",
    price: 15,
    description: "Tradycyjna forma sushi, krewetka na ryżu",
    category: "Nigiri",
    image: "/images/Nigiri/nigiri-krewetka.webp",
  },
  {
    id: "nigiri_tuńczyk 1szt.",
    name: "Nigiri tuńczyk 1szt.",
    price: 17,
    description: "Tradycyjna forma sushi, tuńczyk na ryżu",
    category: "Nigiri",
    image: "/images/Nigiri/nigiri-tuna.webp",
  },
  {
    id: "nigiri_wegorz 1szt.",
    name: "Nigiri węgorz 1szt.",
    price: 17,
    description: "Tradycyjna forma sushi, węgorz na ryżu",
    category: "Nigiri",
    image: "/images/Nigiri/nigiri-wegorz.webp",
  },
  {
    id: "nigiri_malze sw.jakuba 1szt.",
    name: "Nigiri małże św.Jakuba 1szt.",
    price: 17,
    description: "Tradycyjna forma sushi, małże",
    category: "Nigiri",
    image: "/images/Nigiri/nigiri-malze.webp",
  },
  {
    id: "nigiri_osmiornica 1szt.",
    name: "Nigiri ośmiornica 1szt.",
    price: 17,
    description: "Tradycyjna forma sushi, ośmiornica na ryżu",
    category: "Nigiri",
    image: "/images/Nigiri/nigiri-osmiornica.webp",
  },
  {
    id: "nigiri_poledwoca_wolowa 1szt.",
    name: "Nigiri polędwica wołowa 1szt.",
    price: 17,
    description: "Tradycyjna forma sushi, polędwica na ryżu",
    category: "Nigiri",
    image: "/images/Nigiri/nigiri-wolowina.webp",
  },
  {
    id: "sashimi_Gravlax.",
    name: "Sashimi Grawlax (6 szt.)",
    price: 55,
    description:
      "Gravlax, pesto z edamame, ogórek, awokado, marynowana dynia, rukola, ikura",
    category: "Sashimi",
    image: "/images/Sashimi/sashimi-losos.webp",
  },
  {
    id: "sashimi_tunczyk.",
    name: "Sashimi Tuńczyk (6 szt.)",
    price: 62,
    description:
      "Tuńczyk, majonez grzybowy, boczniak mikołajkowy w tempurze, pak choi, ogórek, szczypiorek, kizami wasabi ",
    category: "Sashimi",
    image: "/images/Sashimi/sashimi-tunczyk.webp",
  },
  {
    id: "sashimi_wolowina.",
    name: "Sashimi Wołowina (6 szt.)",
    price: 62,
    description:
      "polędwica wołowa tataki, krewetka w panko, sos kobe, szczypiorek, rukola, piklowana czerwona cebula, ikura ",
    category: "Sashimi",
    image: "/images/Sashimi/sashimi-wolowina.webp",
  },
  {
    id: "zupa_shoyu",
    name: "Shoyu",
    description: "boczek chashu, menma, jajko ajitsuke, nori, dymka, tłuszcz z gęsi",
    price: 49,
    category: "Zupy",
    image: "/images/zupy/szajnochy11-ramen-2-z-12.webp",
  },
  {
    id: "zupa_spicy_shoyu",
    name: "Spicy Shoyu",
    description: "mięso mielone soboro, menma, pak choy, jajko ajitsuke, nori, dymka, olej chilli",
    price: 49,
    category: "Zupy",
    image: "/images/zupy/szajnochy11-ramen-3-z-12.webp",
  },
  {
    id: "zupa_kamo_paitan",
    name: "Kamo Paitan",
    description: "marynowana karkówka, blanszowany szpinak, czerwona cebula, jajko ajitsuke, czips z pietruszki, dymka",
    price: 52,
    category: "Zupy",
    image: "/images/zupy/szajnochy11-ramen-6-z-12.webp",
  },
  {
    id: "zupa_kamo_tantanmen",
    name: "Kamo tantanmen",
    description: "mięso mielone soboro, piklowana biała cebula, pak choy, olej chilli, jajko ajitsuke, sezam",
    price: 52,
    category: "Zupy",
    image: "/images/zupy/szajnochy11-ramen-10-z-12.webp",
  },
  {
    id: "zupa_wege_tantanmen",
    name: "Wege tantanmen",
    description: "wegańskie mięso soboro, piklowana biała cebula, pak choy, kiełki fasoli mung, olej chilli",
    price: 48,
    category: "Zupy",
    image: "/images/zupy/szajnochy11-ramen-11-z-12.webp",
  },
  {
    id: "zupa_shrimp_paitan",
    name: "Shrimp Paitan",
    description: "Krewetki smażone w wędzonym panko, narutomaki, dymka, chipsy z cebuli, nori, jajko ajitsuke, olej krewetkowy",
    price: 52,
    category: "Zupy",
    image: "/images/zupy/Shrimp Paitan.png",
  },
  {
    id: "zupa_kakuni_chintan",
    name: "Glazded Kakuni Chintan",
    description: "Boczek kakuni BBQ, jajko ajitsuke, piklowana czerowna cebula, rukola, grillowany bambus, nori, dymka, olej krewetkowy",
    price: 49,
    category: "Zupy",
    image: "/images/zupy/glazded.png",
  },
  {
    id: "zupa_krewetkowa",
    name: "Tradycyjna zupa krewetkowa",
    price: 30,
    description: "krewetki, warzywa, oliwa kolendrowa",
    category: "Zupy",
    image: "/images/zupy/dsc09940_post.jpg",
  },
  {
    id: "zupa_miso_losos",
    name: "Tradycyjna zupa miso z łososiem",
    price: 23,
    description: "",
    category: "Zupy",
    image: "/images/zupy/zupa-z lososiem.png",
  },
  {
    id: "zupa_miso_tofu",
    name: "Tradycyjna zupa miso z tofu",
    price: 18,
    description: "",
    category: "Zupy",
    image: "/images/zupy/dsc00061_post.jpg",
  },
];

export const menuCategories = {
  Sushi: ["Futomaki", "Hosomaki", "Nigiri", "Sashimi", "Sushi Wege"],
  Zupy: [],
  Zestawy: [],
  "Specjały Szajnochy": [],
  Napoje: [],
};
